### ISSUE TITLE
Show a pretty error message when specified volume does not exist

### ISSUE THREAD

**Issue by SLoeuillet** [Napsty/check_equallogic#11]
Between 846 & 847 :

    if [ -z "${volarray}" ]
        then
        echo "UNKNOWN - This volume (${volume}) does not exist."; exit 3
    fi
should be better, to avoid this kind of cryptic error message :

    awk: line 1: syntax error at or near end of line
    /usr/lib/nagios/plugins/check_snmp_dell_equallogic.sh: line 848: / 1024: syntax error: operand expected (error token is "/ 1024")
    UNKNOWN: should never reach this part```

**Comment by Napsty** [comment]
Hi Stephan,
Please check if it works with this commit: 709a2106b3a6e98fc1a10ffbc6ce7abfbce97d57

**Comment by SLoeuillet** [comment]
Works OK !
