### ISSUE TITLE
Check volume name %age error

### ISSUE THREAD

**Issue by arigaud** [Napsty/check_equallogic#7]
hi!

snmp connection works perfectly, thanks.

But i have an issue with line 850

See below my test, no %age (first issue) and test is OK (second issue)

# ./check_equallogic.sh -C public -H x.x.x.x -t vol -v test-bdd1-bdd-oracle
expr: syntax error
OK - Volumetest-bdd1-bdd-oracle used 90GB of 105GB (%)|'volavail'=112742891520, 'volused'=97108623360

when i suppress [${i}], it works fine but i don't know should it do.

850 : volpercentage=$(expr ${volusedspace[${i}]} \* 100 / ${volavailspace[${i}]})
850 : volpercentage=$(expr ${volusedspace} \* 100 / ${volavailspace})

# ./check_equallogic.sh -C public -H x.x.x.x -t vol -v test-bdd1-bdd-oracle
OK - Volume test-bdd1-bdd-oracle used 90GB of 105GB (86%)|'volavail'=112742891520, 'volused'=97108623360

**Comment by hpschulz** [comment]
Hi, i have a error Message by test the script on a check_mk with the prod-User:

check_equallogic: line 153: syntax error near unexpected token `<'
check_equallogic: line 153: `    done < <(echo "${membernames[*]}" | sed "s/.1.3.6/\n.1.3.6/g" | sed "1d")'

System is a centos 6.5. 

Thanks a lot

**Comment by arigaud** [comment]
Hi hpschulz

This issue is closed, please open your own issue.

(put command result snmpwalk -v 2c -On -c your_community your_host 1.3.6.1.4.1.12740.2.1.1.1.9)
