### ISSUE TITLE
check_equallogic: line 153: syntax error near unexpected token <' 

### ISSUE THREAD

**Issue by hpschulz** [Napsty/check_equallogic#9]
Hi, i have a error Message by test the script on a check_mk with the prod-User:

check_equallogic: line 153: syntax error near unexpected token <' check_equallogic: line 153: done < <(echo "${membernames[*]}" | sed "s/.1.3.6/\n.1.3.6/g" | sed "1d")'

System is a centos 6.5.

Thanks a lot

**Comment by arigaud** [comment]
Hi,

Please put command result snmpwalk -v 2c -On -c your_community your_host 1.3.6.1.4.1.12740.2.1.1.1.9

maybe is empty.

**Comment by hpschulz** [comment]
Hi,

.1.3.6.1.4.1.12740.2.1.1.1.9.1.747453112 = STRING: "PS6100-1"
.1.3.6.1.4.1.12740.2.1.1.1.9.1.1729907221 = STRING: "PS6100-2"
.1.3.6.1.4.1.12740.2.1.1.1.9.1.2103509518 = STRING: "PS4000-1"

thanks a lot.

**Comment by hpschulz** [comment]
Sorry, my mistake. I've forgett a Option. Closed this Issue. Thanks a lot.
